name: '📑 Check Conventional Commits'
description: 'Checks commit messages and validates Conventional Commits'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        COMMITS_API=$(echo "${GITHUB_CONTEXT}" | jq .event.pull_request._links.commits.href)

        if [[ "${COMMITS_API}" != "null" ]]; then
          echo "Commits API : ${COMMITS_API}"
        else
          echo "::error:Could not find commits api url from context"
          exit 1
        fi

        curl --request GET \
          --url ${COMMITS_API} \
          --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --fail | jq

        #gh pr -R octocat/Hello-World view 2279 --json commits
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        GITHUB_TOKEN: ${{ github.token }}