name: '📑 Check Conventional Commits'
description: 'Checks commit messages and validates Conventional Commits'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ${{ github.action_path }}/action.bash
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        GITHUB_TOKEN: ${{ github.token }}
